language: python
dist: focal
sudo: required

before_install:
  - sudo apt-get install -y python3-venv

script:
  - ./utils/deploy_client.sh .
  - source gfa_venv/bin/activate

after_failure:
  - cat /tmp/gfa_venv_pip_log
