language: python
dist: focal

before_install:
  - apt-get install -y python3-venv
  - python --version
  - pip install -U pip

script:
  - bash -x ./utils/deploy_client.sh /tmp
  - source gfa_venv/bin/activate

after_failure:
  - cat /tmp/gfa_venv_pip_log
